/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalyzeCard: typeof import('./src/components/AnalyzeCard.vue')['default']
    ConfusionChart: typeof import('./src/components/ConfusionChart.vue')['default']
    FreqDomainChart: typeof import('./src/components/FreqDomainChart.vue')['default']
    LabelChart: typeof import('./src/components/LabelChart.vue')['default']
    ModuleOne: typeof import('./src/components/modules/ModuleOne.vue')['default']
    ModuleTwo: typeof import('./src/components/modules/ModuleTwo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScatterChart: typeof import('./src/components/ScatterChart.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TEmpty: typeof import('tdesign-vue-next')['Empty']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    TimeDomainChart: typeof import('./src/components/TimeDomainChart.vue')['default']
    TimeFreqChart: typeof import('./src/components/TimeFreqChart.vue')['default']
    TInput: typeof import('tdesign-vue-next')['Input']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TUpload: typeof import('tdesign-vue-next')['Upload']
    TypeLabelInput: typeof import('./src/components/form/TypeLabelInput.vue')['default']
  }
}
