/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalyzeCard: typeof import('./src/components/AnalyzeCard.vue')['default']
    FreqDomainChart: typeof import('./src/components/FreqDomainChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TCheckboxGroup: typeof import('tdesign-vue-next')['CheckboxGroup']
    TEmpty: typeof import('tdesign-vue-next')['Empty']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    TimeDomainChart: typeof import('./src/components/TimeDomainChart.vue')['default']
    TimeFreqChart: typeof import('./src/components/TimeFreqChart.vue')['default']
    TInput: typeof import('tdesign-vue-next')['Input']
    TSpace: typeof import('tdesign-vue-next')['Space']
  }
}
